name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build
      - name: linting typescript
        run: npm run lint
      - name: linting css
        run: npm run lint:css
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run sb:build
        # Установка Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t my-vite-react-app .
      # Запуск Docker-контейнера
      - name: Run Docker container
        run: |
          docker run -d -p 6006:6006 my-vite-react-app
      # Дожидаемся запуска контейнера
      - name: Wait for Storybook to start
        run: npx wait-on http://localhost:6006
      - name: screenshot testing
        run:
          npm run test:ui:ci
          # Останавливаем контейнер
      - name: Stop Docker container
        run: docker stop $(docker ps -q)
